name: Build Magisk/KernelSU Module

on:
  push:
    tags: [ v*.*.* ]

jobs:
  build:
    name: Build Module
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Apt Dependencies
        run: |
          sudo apt update -y && sudo apt upgrade -y
          sudo apt install zip unzip -y

      - name: Make
        shell: bash
        run: |
          zip -9 -r "module.zip" * -x ".git"
          
      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
            files: 'module.zip'
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
